#!/bin/env python3

import os
import sys
import json
import pygit2
import argparse
from pathlib import Path

pgname = "tec-gmux"
pgnver = "v0.0.1"
default_cmd = "show"

"""
TODO:
    1. Pull changes to update plugins
"""

class Repo:
    def __init__(self):
        pass

    def setup(self):
        pass

    def pull(self):
        pass

class Log:
    def __init__(self):
        pass

    def err(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg, file=sys.stderr)
        return 1

    def info(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

    def debug(self, fmt, *arg):
        print(f"{pgname}: " + fmt % arg)
        return 0

class Config:
    def __init__(self):
        self.config = None

    def _get_config_file(self):
        paths = [
            "/".join([os.environ["HOME"], ".tec/pgn/nine.json"]),
            "/".join([os.environ["HOME"], ".config/tec/pgn/nine.json"]),
        ]
        for cfg in paths:
            if os.path.exists(cfg):
                return cfg
        return None

    def _get_defaults(self):
        return {}

    def get(self):
        fname = self._get_config_file()

        if fname == None:
            self.err("no config file is found")
            sys.exit(1)
        with open(fname) as file:
            self.config = json.load(file)
        return self.config

class Nine:
    def __init__(self, pgnbase):
        self.pgnbase = pgnbase
        self.config = Config().get()

    def _get_desc(self, pgn):
        desc = "Tec plugin"
        fname = "/".join([self.pgnbase, pgn, "desc"])

        if os.path.isfile(fname):
            with open(fname, "r") as f:
                desc = f.readline()
                if desc:
                    desc = desc.strip("\n")
        return desc


    def add(self): # Activate plugin
        pass

    def cfg(self): # config show, edit, list, get, set
        for _cfg in self.config["repos"]:
            print(f"{_cfg["name"]}\t{_cfg["link"]}")

    def init(self): # Download plugins
        for cfg in self.config["repos"]:
            repodir = "/".join([self.pgnbase, cfg['name']])
            if not os.path.exists(repodir):
                pygit2.clone_repository(cfg['link'], repodir)

    def rm(self): # Deactiate plugin
        pass

    def show(self):
        path = Path(self.pgnbase)
        plugins = [entry.name for entry in path.iterdir() if entry.is_dir()]

        for pgn in plugins:
            print(f"{pgn}\t{self._get_desc(pgn)}")

    def sync(self): # Git pull
        for cfg in self.config["repos"]:
            print("sync cfg repo:", cfg)
        pass

    def version(self):
        print(f"{pgname}: {pgnver}")

parser = argparse.ArgumentParser(description="Tec plugin manager")
parser.add_argument("-P", "--pgnbase", help="pgn directory base")
parser.add_argument("-T", "--taskbase", help="task directory base")
parser.add_argument("-V", "--version", action="store_true", help="plugin version")
parser.add_argument("cmd", default=default_cmd, nargs='?', type=str, help="subcommand")
#parser.add_argument("taskids", type=str, nargs='*', help="task ID")
args = parser.parse_args()

def main():
    log = Log()
    nine = Nine(args.pgnbase)
    cmd = getattr(nine, args.cmd, None)

    if args.version:
        cmd = getattr(nine, "version", None)

    if cmd is not None:
        res = cmd()
    else:
        res = log.err(f"'{args.cmd}': no such command")
    sys.exit(res)

main()
